theme: jekyll-theme-minimal
title: Faruk Açan
description: My Personal Webpage
logo: /assets/images/profile.jpg
show_downloads: false
education: PhD Student, Boğaziçi University
email: farukacan@gmail.com
occupation: Software Developer